version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: timofeidomnikov/kargain-api
    container_name: backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: npm run start

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
