version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/kargainworld/kargain-api
    container_name: backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
